import { useId } from 'react'
import { Field } from './Field'
import { useT, type Key } from '../i18n'
import type { SearchIconOptions } from '../../../shared/types'

interface Props {
  icon: SearchIconOptions
  icons: { id: string; label: string; svg: string }[]
  onChange: (icon: SearchIconOptions) => void
}

/** Names for the built-in icons; an unknown id falls back to the main process's label. */
const ICON_NAMES: Record<string, Key> = {
  search: 'search.iconSearch',
  'text-search': 'search.iconTextSearch',
  'scan-search': 'search.iconScanSearch',
  'search-circle': 'search.iconSearchCircle',
  'search-square': 'search.iconSearchSquare',
  command: 'search.iconCommand'
}

/** The look of the search icon button: which icon, size, colors, spacing, label. */
export default function SearchIconForm({ icon, icons, onChange }: Props): React.JSX.Element {
  const t = useT()
  const id = useId()
  const set = <K extends keyof SearchIconOptions>(key: K, value: SearchIconOptions[K]): void =>
    onChange({ ...icon, [key]: value })
  return (
    <div className="icon-form">
      <div className="field">
        <span className="field__label" id={`${id}-icon`}>
          {t('search.icon')}
        </span>
        <div className="icon-choices" role="radiogroup" aria-labelledby={`${id}-icon`}>
          {icons.map((choice) => {
            const name = ICON_NAMES[choice.id] ? t(ICON_NAMES[choice.id]) : choice.label
            return (
              <button
                key={choice.id}
                role="radio"
                aria-checked={icon.icon === choice.id}
                aria-label={name}
                title={name}
                className={icon.icon === choice.id ? 'is-active' : ''}
                onClick={() => set('icon', choice.id)}
                // Built-in icons, generated by the app.
                dangerouslySetInnerHTML={{ __html: choice.svg }}
              />
            )
          })}
          <button
            role="radio"
            aria-checked={icon.icon === 'custom'}
            className={`icon-choices__custom${icon.icon === 'custom' ? ' is-active' : ''}`}
            onClick={() => set('icon', 'custom')}
          >
            {t('search.iconCustom')}
          </button>
        </div>
      </div>
      {icon.icon === 'custom' && (
        <Field label={t('search.svgMarkup')} hint={t('search.svgHint')}>
          <textarea
            className="mono"
            rows={4}
            value={icon.svg}
            placeholder={'<svg viewBox="0 0 24 24">…</svg>'}
            onChange={(e) => set('svg', e.target.value)}
          />
        </Field>
      )}
      <div className="grid-2">
        <Field label={t('search.size')}>
          <input
            type="number"
            min={8}
            max={96}
            value={icon.size}
            onChange={(e) => set('size', Number(e.target.value))}
          />
        </Field>
        {icon.icon !== 'custom' ? (
          <Field label={t('search.lineWidth')}>
            <input
              type="number"
              min={0.5}
              max={4}
              step={0.25}
              value={icon.stroke}
              onChange={(e) => set('stroke', Number(e.target.value))}
            />
          </Field>
        ) : (
          <span />
        )}
        <Field label={t('search.padding')}>
          <input
            type="number"
            min={0}
            max={48}
            value={icon.padding}
            onChange={(e) => set('padding', Number(e.target.value))}
          />
        </Field>
        <Field label={t('search.radius')}>
          <input
            type="number"
            min={0}
            max={999}
            value={icon.radius}
            onChange={(e) => set('radius', Number(e.target.value))}
          />
        </Field>
      </div>
      <ColorField
        label={t('search.color')}
        hint={t.rich('search.colorHint', {
          current: <code>currentColor</code>,
          variable: <code>var(--your-color)</code>
        })}
        value={icon.color}
        onChange={(value) => set('color', value)}
      />
      <ColorField
        label={t('search.background')}
        hint={t.rich('search.backgroundHint', { transparent: <code>transparent</code> })}
        value={icon.background}
        onChange={(value) => set('background', value)}
      />
      <Field label={t('search.label')} hint={t('search.labelHint')}>
        <input value={icon.label} onChange={(e) => set('label', e.target.value)} />
      </Field>
    </div>
  )
}

export function ColorField({
  label,
  hint,
  value,
  onChange
}: {
  label: string
  hint: React.ReactNode
  value: string
  onChange: (value: string) => void
}): React.JSX.Element {
  const t = useT()
  const id = useId()
  const hex = /^#[0-9a-f]{6}$/i.test(value.trim()) ? value.trim() : '#000000'
  return (
    <div className="field">
      <label className="field__label" htmlFor={`${id}-value`}>
        {label}
      </label>
      <div className="input-group">
        {/* Shows the value as typed (currentColor, var(), transparent), not just hex. */}
        <label className="color-swatch" title={t('search.pickColor', { label })}>
          <span style={{ background: value || 'transparent' }} aria-hidden="true" />
          <input
            type="color"
            aria-label={t('search.pickColor', { label })}
            value={hex}
            onChange={(e) => onChange(e.target.value)}
          />
        </label>
        <input
          id={`${id}-value`}
          className="mono"
          aria-describedby={`${id}-hint`}
          value={value}
          onChange={(e) => onChange(e.target.value)}
        />
      </div>
      <span className="field__hint" id={`${id}-hint`}>
        {hint}
      </span>
    </div>
  )
}
