import type { Msg } from '../types'

/** App shell: sidebar, top bar, drafts, projects, page list. */
export default {
  // Views (sidebar + top bar)
  viewPages: 'Pages',
  viewBlog: 'Blog',
  viewComponents: 'Shared components',
  viewMedia: 'Media',
  viewSeo: 'SEO',
  viewSearch: 'Site search',
  viewAi: 'Template editing (AI)',
  viewPublish: 'Publish',
  viewProject: 'Project settings',
  viewSettings: 'App settings',
  sections: 'Sections',

  // Sidebar
  switchProject: 'Switch project ({shortcut})',
  noProjectOpen: 'No project open',
  openAProject: 'Open a project',
  aiConnected: 'AI connected: {clients}',
  proposalsWaiting: {
    one: '{count} proposal waiting',
    other: '{count} proposals waiting'
  } satisfies Msg,
  publishSite: 'Publish site',

  // Top bar
  dismissError: 'Dismiss this error',
  scheduledToast: '“{label}” goes live {at}. You can follow it in Publish.',
  scheduledToastUntil:
    '“{label}” goes live {at} and comes down {until}. You can follow it in Publish.',
  scheduledOtherProject: '{project}: {message}',

  // Drafts
  savedPages: { one: 'Saved {count} page', other: 'Saved {count} pages' } satisfies Msg,
  nothingToSave: 'Nothing to save',
  skippedShared: {
    one: '{count} shared edit skipped: the content differs there',
    other: '{count} shared edits skipped: the content differs there'
  } satisfies Msg,
  skippedDetail: '{component} on {page}: differs from {from}',
  undoSave: 'Undo save',
  unsavedSummary: {
    one: 'Unsaved edits on {count} page',
    other: 'Unsaved edits on {count} pages'
  } satisfies Msg,
  editsCount: { one: '{count} edit', other: '{count} edits' } satisfies Msg,
  fromShared: {
    one: '{count} from shared blocks',
    other: '{count} from shared blocks'
  } satisfies Msg,
  seoChanges: 'SEO',
  discardPage: 'Discard edits on {page}',
  staleNote: 'Changed on disk, so these edits will be dropped: {pages}',
  confirmDiscardAll: 'Discard every unsaved edit?',
  discardAll: 'Discard all',
  schedule: 'Schedule…',
  scheduleHint: 'Save these edits at a set time instead of now',
  saveAll: 'Save all',
  saveAllHint: 'Write every edit to the site folder ({shortcut})',

  // Projects
  projects: 'Projects',
  addProject: 'Add project…',
  searchProjects: 'Search recent projects',
  noMatch: 'No project matches “{query}”.',
  noRecent: 'No recent projects yet. Add a site folder to start.',
  currentBadge: 'open',
  unsavedBadge: { one: '{count} unsaved', other: '{count} unsaved' } satisfies Msg,
  deploysTo: 'Deploys to {name}',
  removeFromList: 'Remove {name} from the list (the folder is not touched)',

  // Page list
  openSiteTitle: 'Open a site',
  openSiteBody:
    'Pick the folder with your site’s HTML files. It stays the source of truth: CraftPages edits the files in place.',
  openProjectButton: 'Open project…',
  noPages: 'No HTML pages in this folder yet.',
  colTitle: 'Title',
  colFile: 'File',
  colSize: 'Size',
  badgeBlog: 'blog',
  generatedHint: 'Generated by the blog: edit the post in Blog',
  editPageHint: 'Edit {title}',
  untitled: 'Untitled'
} satisfies Record<string, Msg>
